Repository strongbox/strongbox-parent, pull requests merged in 2020-10, with the labels that each got.

#80 issue-1872: Upgrade the maven-jar-plugin from 3.0.2 to 3.2.0
  pom.xml
Labels: GraceHopperOSD

#82 Issue#1850: Upgrade our slf4j dependencies from 1.7.24 to 1.7.30
  pom.xml
Labels: GraceHopperOSD, expecting-icla

#83 Upgrade the maven-source-plugin from 2.2.1 to 3.2.1 #1875
  pom.xml
Labels: GraceHopperOSD

#100 Issue 1901: Copy our pull request template to the rest of the Strongbox projects
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest

#92 Issue 1856: Upgrade our awaitility dependencies from 3.1.2 to 4.0.3
  pom.xml
Labels: expecting-icla

#85 Issue-1857: Upgrade swagger dependencies from 1.5.18 to 1.6.2
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#108 Issue 1873
  pom.xml
Labels: hacktoberfest-accepted

#111 Issue 1916: update version of jsonschema2pojo needed in strongbox-npm-metadata
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#116 Issue 1862: Update org.apache.commons:commons-collections4 from version 4.3 to 4.4
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#117 Issue 1861: Upgrade commons-io:commons-io from 2.6 to 2.8.0
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#119 Updating gmavenplus-plugin for issue 1923
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#122 Issue 1848: Upgrade Jetty to 9.4.33.v20201020
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#123 Issue 1870: Upgrade the maven-surefire-plugin and maven-failsafe-plugin to 3.0.0-M5
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#109 issues/1775: Upgrade to Cassandra to 4.0-beta2
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#125 issues-1943: fixed parent pom version
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#126 issues-1849: remove ehcache dependencies
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#124 Issue 1871: Upgrade the maven-resources-plugin from 3.0.2 to 3.2.0
  pom.xml
Labels: expecting-icla, hacktoberfest, hacktoberfest-accepted

#127 Issue 1942: Add explicit versions for the plugins that are missing such in the strongbox-parent
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted

#107 Issue 1865: Add a rule using the maven-enforcer plugin that requires JDK 8
  pom.xml
Labels: hacktoberfest, hacktoberfest-accepted
